# 博客基本信息
title: taciturn-hg's Blog        # 博客标题
description: 记录我的学习笔记与项目经验
url: "https://taciturn-hg.github.io"  # 博客地址
baseurl: ""                 # 仓库名，如果是用户主页就留空
language: zh-CN

# 作者信息
author:
  name: "HouGuo"
  avatar: "/assets/images/avatar.png"  # 头像路径，可选
  email: "w430390470@example.com"
  bio: "大二全栈开发初学者，Java & Python"

# 主题设置
theme: minimal-mistakes-jekyll
paginate: 5                 # 每页显示文章数
paginate_path: "/page:num/"

# 社交链接
social:
  github: "https://github.com/taciturn-hg"

# 所有文章 URL 规则
permalink: /:categories/:year/:month/:day/:title/

# 插件
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

