# 博客基本信息
title: taciturn-hg's Blog
description: 记录我的学习笔记与项目经验
url: "https://taciturn-hg.github.io"
baseurl: ""
language: zh-CN

# 作者信息
author:
  name: "HouGuo"
  avatar: "/assets/images/avatar.png"
  email: "w430390470@example.com"
  bio: "大二全栈开发初学者，Java & Python"

# 主题设置
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"

# 分页设置
paginate: 5
paginate_path: "/page:num/"

# 导航栏显示页面
header_pages:
  - index.md
  - about.md
  - archive.md

# 社交链接
social:
  github: "https://github.com/taciturn-hg"

# 文章 URL 规则
permalink: /:categories/:year/:month/:day/:title/

# 插件
plugins:
  - jekyll-include-cache

collections:
  posts:
    output: true

# 全局文章默认配置
defaults:
  - scope:
      path: ""        # "" 表示整个站点
      type: "posts"   # 仅应用于文章
    values:
      toc: true                # 全局开启目录
      toc_label: "目录"        # 目录标题
      toc_sticky: true         # 侧边栏目录跟随滚动
      author_profile: true     # 显示作者信息
